import { StyleSheet } from "react-native";
import { Colors, shadows } from "@/constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  errorText: {
    fontSize: 16,
    fontFamily: "Poppins_500Medium",
    color: Colors.textSecondary,
  },
  backLink: {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.primary,
    marginTop: 12,
  },
  heroSection: {},
  heroOverlay: {
    flex: 1,
    justifyContent: "space-between",
    padding: 16,
    paddingBottom: 20,
  },
  heroNav: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  navButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  heroActions: { flexDirection: "row", gap: 8 },
  heroContent: { gap: 8 },
  heroBadges: { flexDirection: "row", gap: 8 },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
  },
  heroBadgeText: {
    fontSize: 12,
    fontFamily: "Poppins_600SemiBold",
    color: "#FFF",
  },
  heroTitle: {
    fontSize: 26,
    fontFamily: "Poppins_700Bold",
    lineHeight: 32,
  },
  heroOrganizer: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    color: "rgba(255,255,255,0.85)",
  },
  countdownContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 4,
  },
  countdownRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  countdownBox: {
    backgroundColor: Colors.surface,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 18,
    alignItems: "center",
    minWidth: 72,
    ...shadows.small,
  },
  countdownNumber: {
    fontSize: 24,
    fontFamily: "Poppins_700Bold",
    color: Colors.primary,
  },
  countdownLabel: {
    fontSize: 11,
    fontFamily: "Poppins_500Medium",
    color: Colors.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 2,
  },
  countdownSeparator: {
    fontSize: 22,
    fontFamily: "Poppins_700Bold",
    color: Colors.textTertiary,
  },
  countdownEndedBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  countdownEndedText: {
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.textSecondary,
  },
  infoCards: { paddingHorizontal: 20, paddingTop: 20, gap: 12 },
  infoCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 16,
    gap: 14,
    ...shadows.small,
  },
  infoIconBg: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  infoLabel: {
    fontSize: 11,
    fontFamily: "Poppins_500Medium",
    color: Colors.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  infoValue: {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.text,
  },
  infoSub: {
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
    marginTop: 1,
  },
  sectionDivider: {
    paddingHorizontal: 20,
    marginTop: 28,
    alignItems: "center",
  },
  accentBar: {
    width: 40,
    height: 3,
    borderRadius: 2,
    backgroundColor: Colors.primary + "25",
  },
  section: { paddingHorizontal: 20, marginTop: 20 },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
    color: Colors.text,
    marginBottom: 12,
  },
  capacityRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  capacityLabel: {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.textSecondary,
  },
  capacityBar: {
    height: 8,
    backgroundColor: Colors.backgroundSecondary,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 8,
  },
  capacityFill: { height: "100%", borderRadius: 4 },
  capacityDetails: { flexDirection: "row", justifyContent: "space-between" },
  capacityText: {
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
  },
  description: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
    lineHeight: 22,
  },
  tierCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 18,
    marginBottom: 10,
    ...shadows.small,
  },
  tierInfo: { gap: 2 },
  tierName: {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.text,
  },
  tierAvail: {
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
  },
  tierPrice: {
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
    color: Colors.primary,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    marginBottom: 12,
  },
  detailText: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
    flex: 1,
    lineHeight: 20,
  },
  whosGoingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  avatarStack: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: Colors.surface,
  },
  whosGoingInfo: {
    gap: 2,
  },
  whosGoingCount: {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.text,
  },
  whosGoingOthers: {
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
  },
  relatedCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 14,
    marginBottom: 10,
    gap: 12,
    ...shadows.small,
  },
  relatedSwatch: {
    width: 52,
    height: 52,
    borderRadius: 14,
  },
  relatedInfo: {
    flex: 1,
    gap: 2,
  },
  relatedTitle: {
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.text,
  },
  relatedMeta: {
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
  },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.surface,
    paddingHorizontal: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.border + "40",
    ...shadows.medium,
  },
  priceSection: {},
  priceFrom: {
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
  },
  priceBig: { fontSize: 22, fontFamily: "Poppins_700Bold", color: Colors.text },
  buyButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: Colors.primary,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 28,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  buyText: { fontSize: 16, fontFamily: "Poppins_600SemiBold", color: "#FFF" },
  ticketButtonsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  externalButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 14,
    paddingHorizontal: 14,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + "10",
  },
  externalButtonText: {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.primary,
  },
  // Feedback styles
  feedbackThanks: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: Colors.secondary + "12",
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 18,
  },
  feedbackThanksText: {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.secondary,
  },
  feedbackPrompt: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
    marginBottom: 14,
  },
  starsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 16,
  },
  feedbackSubmitBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 28,
    alignSelf: "flex-start",
  },
  feedbackSubmitText: {
    fontSize: 14,
    fontFamily: "Poppins_600SemiBold",
    color: "#FFF",
  },
  discoveryFeedbackRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  discoveryFeedbackLabel: {
    fontSize: 13,
    fontFamily: "Poppins_500Medium",
    color: Colors.textSecondary,
  },
  discoveryFeedbackBtns: {
    flexDirection: "row",
    gap: 10,
  },
  discoveryFeedbackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: Colors.backgroundSecondary,
  },
  discoveryFeedbackBtnText: {
    fontSize: 13,
    fontFamily: "Poppins_500Medium",
    color: Colors.textSecondary,
  },
  earlyAccessBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 122, 255, 0.08)",
    marginHorizontal: 20,
    marginTop: 4,
    marginBottom: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    gap: 5,
    borderWidth: 1,
    borderColor: "#D6EAF8",
  },
  earlyAccessText: { fontSize: 12, fontWeight: "600", color: "#1A5276" },
  earlyAccessDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#2E86C1",
    opacity: 0.4,
  },
  educationCard: {
    backgroundColor: "rgba(255, 149, 0, 0.08)",
    borderRadius: 16,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#8B4513",
  },
  educationHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  educationIconBg: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#8B451318",
    alignItems: "center",
    justifyContent: "center",
  },
  educationTitle: {
    fontSize: 16,
    fontFamily: "Poppins_700Bold",
    color: "#3E2723",
  },
  educationBody: {
    fontSize: 13,
    fontFamily: "Poppins_400Regular",
    color: "#5D4037",
    lineHeight: 20,
    marginBottom: 8,
  },
  educationHighlight: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    backgroundColor: "rgba(0, 122, 255, 0.08)",
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
  },
  educationHighlightText: {
    flex: 1,
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: "#1A5276",
    lineHeight: 18,
  },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: Colors.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    maxHeight: "80%",
  },
  handle: {
    width: 36,
    height: 5,
    borderRadius: 3,
    backgroundColor: Colors.textTertiary,
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 6,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderLight,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Poppins_700Bold",
    color: Colors.text,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  sectionLabel: {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 10,
  },
  tierOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.background,
    borderRadius: 12,
    padding: 16,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: "transparent",
  },
  tierOptionSelected: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + "08",
  },
  tierOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: Colors.textTertiary,
    alignItems: "center",
    justifyContent: "center",
  },
  radioOuterSelected: {
    borderColor: Colors.primary,
  },
  radioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: Colors.primary,
  },
  tierOptionName: {
    fontSize: 15,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.text,
  },
  tierOptionAvail: {
    fontSize: 12,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
    marginTop: 1,
  },
  tierOptionPrice: {
    fontSize: 17,
    fontFamily: "Poppins_700Bold",
    color: Colors.text,
  },
  quantityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    marginBottom: 24,
  },
  quantityBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.background,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  quantityBtnDisabled: {
    opacity: 0.4,
  },
  quantityText: {
    fontSize: 22,
    fontFamily: "Poppins_700Bold",
    color: Colors.text,
    minWidth: 40,
    textAlign: "center",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
    marginBottom: 16,
  },
  totalLabel: {
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    color: Colors.textSecondary,
  },
  totalValue: {
    fontSize: 22,
    fontFamily: "Poppins_700Bold",
    color: Colors.text,
  },
  purchaseBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 16,
    width: "100%",
  },
  purchaseBtnText: {
    fontSize: 16,
    fontFamily: "Poppins_600SemiBold",
    color: "#FFF",
  },
  cashbackNote: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 122, 255, 0.08)",
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    gap: 6,
  },
  cashbackNoteText: {
    fontSize: 13,
    color: "#1A5276",
    fontWeight: "500",
    flex: 1,
  },
  upgradeNote: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 122, 255, 0.08)",
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: "#D6EAF8",
  },
  upgradeNoteText: {
    fontSize: 12,
    color: "#2E86C1",
    fontWeight: "500",
    flex: 1,
  },
  buyModeRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  buyModeBtn: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: Colors.background,
    borderWidth: 2,
    borderColor: "transparent",
  },
  buyModeBtnActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primary + "08",
  },
  buyModeText: {
    fontSize: 12,
    fontFamily: "Poppins_500Medium",
    color: Colors.textSecondary,
  },
  savingsBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(52, 199, 89, 0.08)",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#C8F0DB",
  },
  savingsText: {
    fontSize: 13,
    fontFamily: "Poppins_600SemiBold",
    color: "#27AE60",
  },
  priceSummary: {
    backgroundColor: Colors.background,
    borderRadius: 12,
    padding: 14,
    marginTop: 8,
    marginBottom: 16,
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
  },
  priceRowLabel: {
    fontSize: 14,
    fontFamily: "Poppins_400Regular",
    color: Colors.textSecondary,
  },
  priceRowValue: {
    fontSize: 14,
    fontFamily: "Poppins_500Medium",
    color: Colors.text,
  },
  totalDivider: {
    height: 1,
    backgroundColor: Colors.borderLight,
    marginVertical: 8,
  },
});
