import { StyleSheet } from 'react-native';

export const CORNER = 28;
export const CORNER_W = 4;

export const s = StyleSheet.create({
  container:           { flex: 1 },
  header:              { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 10 },
  headerBtn:           { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  headerTitle:         { fontSize: 18, fontFamily: 'Poppins_700Bold' },
  headerRight:         { width: 38, alignItems: 'flex-end' },
  toggleContainer:     { flexDirection: 'row', marginHorizontal: 20, borderRadius: 12, padding: 4, gap: 4 },
  toggleTab:           { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, borderRadius: 10 },
  toggleText:          { fontSize: 13, fontFamily: 'Poppins_600SemiBold' },
  statsBar:            { flexDirection: 'row', marginHorizontal: 20, marginTop: 12, borderRadius: 14, padding: 14, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  statItem:            { flex: 1, alignItems: 'center', gap: 2 },
  statNum:             { fontSize: 20, fontFamily: 'Poppins_700Bold' },
  statLabel:           { fontSize: 10, fontFamily: 'Poppins_500Medium' },
  statDivider:         { width: 1, marginVertical: 2 },
  cameraContainer:     { height: 300, marginHorizontal: 20, marginTop: 14, borderRadius: 20, overflow: 'hidden', position: 'relative' },
  camera:              { flex: 1 },
  cameraOverlay:       { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center' },
  cameraFrame:         { width: 210, height: 210, position: 'relative' },
  cCorner:             { position: 'absolute', width: CORNER, height: CORNER },
  cTL:                 { top: 0, left: 0,    borderTopWidth: CORNER_W,    borderLeftWidth: CORNER_W,  borderColor: '#FFF', borderTopLeftRadius: 8 },
  cTR:                 { top: 0, right: 0,   borderTopWidth: CORNER_W,    borderRightWidth: CORNER_W, borderColor: '#FFF', borderTopRightRadius: 8 },
  cBL:                 { bottom: 0, left: 0, borderBottomWidth: CORNER_W, borderLeftWidth: CORNER_W,  borderColor: '#FFF', borderBottomLeftRadius: 8 },
  cBR:                 { bottom: 0, right: 0,borderBottomWidth: CORNER_W, borderRightWidth: CORNER_W, borderColor: '#FFF', borderBottomRightRadius: 8 },
  cameraHint:          { marginTop: 230, color: '#FFF', fontSize: 14, fontFamily: 'Poppins_500Medium', textShadowColor: 'rgba(0,0,0,0.7)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 4 },
  closeCameraBtn:      { position: 'absolute', top: 12, right: 12 },
  scanInputSection:    { marginHorizontal: 20, marginTop: 14, gap: 10 },
  camScanBtn:          { borderRadius: 16, overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  camScanGradient:     { flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: 22, paddingVertical: 18 },
  camScanTitle:        { fontSize: 17, fontFamily: 'Poppins_700Bold', color: '#FFF' },
  camScanSub:          { fontSize: 12, fontFamily: 'Poppins_400Regular', color: 'rgba(255,255,255,0.8)', marginTop: 1 },
  orRow:               { flexDirection: 'row', alignItems: 'center', gap: 12, marginVertical: 4 },
  orLine:              { flex: 1, height: 1 },
  orText:              { fontSize: 12, fontFamily: 'Poppins_500Medium' },
  inputRow:            { flexDirection: 'row', gap: 10 },
  codeInput:           { flex: 1, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14, fontSize: 16, fontFamily: 'Poppins_500Medium', borderWidth: 1 },
  scanBtn:             { width: 52, height: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  scanBtnDisabled:     { opacity: 0.6 },
  resultWrapper:       { marginHorizontal: 20, marginTop: 14 },
  historySection:      { marginHorizontal: 20, marginTop: 20 },
  historySectionHeader:{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  historyTitle:        { fontSize: 15, fontFamily: 'Poppins_700Bold' },
  historyItem:         { flexDirection: 'row', alignItems: 'center', gap: 10, borderRadius: 12, padding: 12, marginBottom: 8, borderLeftWidth: 3, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  historyIconWrap:     { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  historyEventTitle:   { fontSize: 14, fontFamily: 'Poppins_600SemiBold' },
  historyStatus:       { fontSize: 12, fontFamily: 'Poppins_400Regular', marginTop: 1 },
  historyTierChip:     { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },
  historyTierText:     { fontSize: 11, fontFamily: 'Poppins_600SemiBold' },
  emptyState:          { alignItems: 'center', paddingTop: 32, paddingHorizontal: 40, gap: 12 },
  emptyIconBg:         { width: 88, height: 88, borderRadius: 26, marginBottom: 4, alignItems: 'center', justifyContent: 'center' },
  emptyTitle:          { fontSize: 20, fontFamily: 'Poppins_700Bold' },
  emptyDesc:           { fontSize: 14, fontFamily: 'Poppins_400Regular', textAlign: 'center', lineHeight: 22 },
  lookupOverlay:       { ...StyleSheet.absoluteFillObject, zIndex: 200, alignItems: 'center', justifyContent: 'center', gap: 12 },
  lookupText:          { fontSize: 16, fontFamily: 'Poppins_600SemiBold' },
  cameraStartBtn:      { borderRadius: 20, padding: 24, alignItems: 'center', gap: 8, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4, elevation: 2 },
  cameraIconCircle:    { width: 72, height: 72, borderRadius: 36, alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
  cameraStartTitle:    { fontSize: 18, fontFamily: 'Poppins_700Bold' },
  cameraStartSub:      { fontSize: 13, fontFamily: 'Poppins_400Regular', textAlign: 'center' },
  cpCard:              { marginHorizontal: 20, marginTop: 14, borderRadius: 20, padding: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 12, elevation: 6 },
  cpCardHeader:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  cpAvatar:            { width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center' },
  cpAvatarText:        { fontSize: 22, fontFamily: 'Poppins_700Bold' },
  closeBtn:            { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  cpName:              { fontSize: 22, fontFamily: 'Poppins_700Bold', marginBottom: 2 },
  cpUsername:          { fontSize: 14, fontFamily: 'Poppins_400Regular', marginBottom: 12 },
  cpChipRow:           { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  cpIdChip:            { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  cpIdText:            { fontSize: 13, fontFamily: 'Poppins_600SemiBold' },
  cpTierChip:          { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 20 },
  cpTierText:          { fontSize: 12, fontFamily: 'Poppins_600SemiBold' },
  cpLocationRow:       { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  cpLocationText:      { fontSize: 13, fontFamily: 'Poppins_400Regular' },
  cpBio:               { fontSize: 14, fontFamily: 'Poppins_400Regular', marginBottom: 10, lineHeight: 20 },
  cpActions:           { flexDirection: 'row', gap: 10, marginTop: 10 },
  cpActionBtn:         { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12, borderRadius: 14 },
  cpActionText:        { fontSize: 13, fontFamily: 'Poppins_600SemiBold' },
  hintSection:         { marginHorizontal: 20, marginTop: 14, borderRadius: 16, padding: 18, gap: 14 },
  hintTitle:           { fontSize: 15, fontFamily: 'Poppins_700Bold' },
  hintItem:            { flexDirection: 'row', alignItems: 'center', gap: 12 },
  hintLabel:           { fontSize: 13, fontFamily: 'Poppins_600SemiBold' },
  hintExample:         { fontSize: 12, fontFamily: 'Poppins_400Regular' },
});
