import { StyleSheet } from 'react-native';

export const CORNER = 28;
export const CORNER_W = 4;

export const getStyles = (colors: any) => StyleSheet.create({
  container:           { flex: 1, backgroundColor: '#0B0B14' },
  header:              { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 10, zIndex: 10 },
  headerBtn:           { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  headerTitle:         { fontSize: 18, fontFamily: 'Poppins_700Bold', color: '#FFFFFF' },
  headerRight:         { width: 44, alignItems: 'flex-end' },
  toggleContainer:     { flexDirection: 'row', marginHorizontal: 20, borderRadius: 16, padding: 4, gap: 4, backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  toggleTab:           { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 12, borderRadius: 12 },
  toggleText:          { fontSize: 13, fontFamily: 'Poppins_600SemiBold', color: 'rgba(255,255,255,0.5)' },
  statsBar:            { flexDirection: 'row', marginHorizontal: 20, marginTop: 12, borderRadius: 16, padding: 16, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  statItem:            { flex: 1, alignItems: 'center', gap: 2 },
  statNum:             { fontSize: 22, fontFamily: 'Poppins_700Bold' },
  statLabel:           { fontSize: 11, fontFamily: 'Poppins_500Medium', color: 'rgba(255,255,255,0.5)' },
  statDivider:         { width: 1, marginVertical: 4, backgroundColor: 'rgba(255,255,255,0.1)' },
  cameraContainer:     { height: 320, marginHorizontal: 20, marginTop: 14, borderRadius: 24, overflow: 'hidden', position: 'relative', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  camera:              { flex: 1 },
  cameraOverlay:       { ...StyleSheet.absoluteFillObject, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(0,0,0,0.3)' },
  cameraFrame:         { width: 220, height: 220, position: 'relative' },
  cCorner:             { position: 'absolute', width: CORNER, height: CORNER },
  cTL:                 { top: 0, left: 0,    borderTopWidth: CORNER_W,    borderLeftWidth: CORNER_W,  borderColor: '#FFF', borderTopLeftRadius: 16 },
  cTR:                 { top: 0, right: 0,   borderTopWidth: CORNER_W,    borderRightWidth: CORNER_W, borderColor: '#FFF', borderTopRightRadius: 16 },
  cBL:                 { bottom: 0, left: 0, borderBottomWidth: CORNER_W, borderLeftWidth: CORNER_W,  borderColor: '#FFF', borderBottomLeftRadius: 16 },
  cBR:                 { bottom: 0, right: 0,borderBottomWidth: CORNER_W, borderRightWidth: CORNER_W, borderColor: '#FFF', borderBottomRightRadius: 16 },
  cameraHint:          { marginTop: 240, color: '#FFF', fontSize: 14, fontFamily: 'Poppins_600SemiBold', textShadowColor: 'rgba(0,0,0,0.8)', textShadowOffset: { width: 0, height: 2 }, textShadowRadius: 6 },
  closeCameraBtn:      { position: 'absolute', top: 16, right: 16 },
  scanInputSection:    { marginHorizontal: 20, marginTop: 16, gap: 12 },
  camScanBtn:          { borderRadius: 20, overflow: 'hidden' },
  camScanGradient:     { flexDirection: 'row', alignItems: 'center', gap: 16, paddingHorizontal: 24, paddingVertical: 20 },
  camScanTitle:        { fontSize: 18, fontFamily: 'Poppins_700Bold', color: '#FFF' },
  camScanSub:          { fontSize: 13, fontFamily: 'Poppins_400Regular', color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  orRow:               { flexDirection: 'row', alignItems: 'center', gap: 12, marginVertical: 8 },
  orLine:              { flex: 1, height: 1, backgroundColor: 'rgba(255,255,255,0.05)' },
  orText:              { fontSize: 12, fontFamily: 'Poppins_500Medium', color: 'rgba(255,255,255,0.4)' },
  inputRow:            { flexDirection: 'row', gap: 12 },
  codeInput:           { flex: 1, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 16, fontSize: 16, fontFamily: 'Poppins_500Medium', backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', color: '#FFFFFF' },
  scanBtn:             { width: 56, height: 56, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  scanBtnDisabled:     { opacity: 0.6 },
  resultWrapper:       { marginHorizontal: 20, marginTop: 16 },
  historySection:      { marginHorizontal: 20, marginTop: 24 },
  historySectionHeader:{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  historyTitle:        { fontSize: 16, fontFamily: 'Poppins_700Bold', color: '#FFFFFF' },
  historyItem:         { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 16, padding: 14, marginBottom: 10, borderLeftWidth: 4, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  historyIconWrap:     { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  historyEventTitle:   { fontSize: 15, fontFamily: 'Poppins_600SemiBold', color: '#FFFFFF' },
  historyStatus:       { fontSize: 13, fontFamily: 'Poppins_400Regular', marginTop: 2 },
  historyTierChip:     { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  historyTierText:     { fontSize: 11, fontFamily: 'Poppins_600SemiBold' },
  emptyState:          { alignItems: 'center', paddingTop: 40, paddingHorizontal: 40, gap: 16 },
  emptyIconBg:         { width: 96, height: 96, borderRadius: 32, marginBottom: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.05)' },
  emptyTitle:          { fontSize: 22, fontFamily: 'Poppins_700Bold', color: '#FFFFFF' },
  emptyDesc:           { fontSize: 15, fontFamily: 'Poppins_400Regular', textAlign: 'center', lineHeight: 24, color: 'rgba(255,255,255,0.6)' },
  lookupOverlay:       { ...StyleSheet.absoluteFillObject, zIndex: 200, alignItems: 'center', justifyContent: 'center', gap: 16, backgroundColor: 'rgba(11,11,20,0.9)' },
  lookupText:          { fontSize: 16, fontFamily: 'Poppins_600SemiBold', color: '#FFFFFF' },
  cameraStartBtn:      { borderRadius: 24, padding: 28, alignItems: 'center', gap: 10, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  cameraIconCircle:    { width: 80, height: 80, borderRadius: 40, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  cameraStartTitle:    { fontSize: 20, fontFamily: 'Poppins_700Bold', color: '#FFFFFF' },
  cameraStartSub:      { fontSize: 14, fontFamily: 'Poppins_400Regular', textAlign: 'center', color: 'rgba(255,255,255,0.6)' },
  cpCard:              { marginHorizontal: 20, marginTop: 16, borderRadius: 24, padding: 24, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  cpCardHeader:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  cpAvatar:            { width: 72, height: 72, borderRadius: 36, alignItems: 'center', justifyContent: 'center' },
  cpAvatarText:        { fontSize: 24, fontFamily: 'Poppins_700Bold' },
  closeBtn:            { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  cpName:              { fontSize: 24, fontFamily: 'Poppins_700Bold', marginBottom: 2, color: '#FFFFFF' },
  cpUsername:          { fontSize: 15, fontFamily: 'Poppins_400Regular', marginBottom: 16, color: 'rgba(255,255,255,0.5)' },
  cpChipRow:           { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 16 },
  cpIdChip:            { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 12 },
  cpIdText:            { fontSize: 14, fontFamily: 'Poppins_600SemiBold' },
  cpTierChip:          { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12 },
  cpTierText:          { fontSize: 13, fontFamily: 'Poppins_600SemiBold' },
  cpLocationRow:       { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  cpLocationText:      { fontSize: 14, fontFamily: 'Poppins_400Regular', color: 'rgba(255,255,255,0.6)' },
  cpBio:               { fontSize: 15, fontFamily: 'Poppins_400Regular', marginBottom: 14, lineHeight: 22, color: 'rgba(255,255,255,0.7)' },
  cpActions:           { flexDirection: 'row', gap: 12, marginTop: 12 },
  cpActionBtn:         { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  cpActionText:        { fontSize: 14, fontFamily: 'Poppins_600SemiBold' },
  hintSection:         { marginHorizontal: 20, marginTop: 16, borderRadius: 20, padding: 20, gap: 16, backgroundColor: 'rgba(255,255,255,0.03)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)' },
  hintTitle:           { fontSize: 16, fontFamily: 'Poppins_700Bold', color: '#FFFFFF' },
  hintItem:            { flexDirection: 'row', alignItems: 'center', gap: 14 },
  hintLabel:           { fontSize: 14, fontFamily: 'Poppins_600SemiBold', color: '#FFFFFF' },
  hintExample:         { fontSize: 13, fontFamily: 'Poppins_400Regular', color: 'rgba(255,255,255,0.5)' },
});
